nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= v2.9.3 < 2.10.0"
    catalog.cattle.io/ui-extensions-version: ">= 2.0.2 < 3"
